DROP TABLE IF EXISTS hours;
DROP TABLE IF EXISTS paycheck;
DROP TABLE IF EXISTS job;
DROP TABLE IF EXISTS claim;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS worker;
DROP TABLE IF EXISTS employer;
DROP TABLE IF EXISTS non_profit;


/* This is a very simple table for a mysql-php example */

CREATE TABLE Users (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR (30) NOT NULL,
  phone VARCHAR (15) NOT NULL,
  hashedPass VARCHAR(255) NOT NULL,
  email VARCHAR(45) UNIQUE NOT NULL,
  PRIMARY KEY (id)
);


CREATE TABLE employer (
	EID INT unsigned AUTO_INCREMENT,
	E_NAME VARCHAR (30) NOT NULL,
	ADDRESS VARCHAR (100) NOT NULL,
	E_EMAIL VARCHAR (40) NOT NULL,
	PRIMARY KEY (EID)
);

CREATE TABLE job (
	JID INT unsigned AUTO_INCREMENT,
	id INT NOT NULL,
	EID INT UNSIGNED NOT NULL,
    JOB_TITLE VARCHAR (40) NOT NULL,
    HOURLY_WAGE FLOAT (5,2) NOT NULL,
	PRIMARY KEY (JID, id, EID),
	CONSTRAINT fk_job_id FOREIGN KEY (id) REFERENCES Users (id),
	CONSTRAINT fk_job_eid FOREIGN KEY (EID) REFERENCES employer (EID)
);

CREATE TABLE hours (
    HID INT UNSIGNED AUTO_INCREMENT,
	JID INT UNSIGNED NOT NULL,
	DAILY_HOURS FLOAT NOT NULL,
	DAILY_HOURS_DATE DATE NOT NULL,
	PRIMARY KEY (HID),
	CONSTRAINT fk_hours_jid FOREIGN KEY (JID) REFERENCES job (JID)
);

CREATE TABLE paycheck (
    PID INT UNSIGNED AUTO_INCREMENT,
	JID INT UNSIGNED NOT NULL,
	HOURLY_WAGE FLOAT (5,2) NOT NULL,
	NET_PAY FLOAT (5,2) NOT NULL,
	HOURS_PAID_FOR FLOAT NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	PRIMARY KEY (PID),
	CONSTRAINT fk_paycheck_jid FOREIGN KEY (JID) REFERENCES job (JID)
);

CREATE TABLE claim (
    CID INT unsigned AUTO_INCREMENT,
	id INT NOT NULL,
	EID INT UNSIGNED NOT NULL,
    CLAIM_DATE_START DATE NOT NULL,
    CLAIM_DATE_END DATE NOT NULL,
    CLAIM_HOURS FLOAT NOT NULL,
	PRIMARY KEY (CID),
	CONSTRAINT fk_claim_id FOREIGN KEY (id) REFERENCES Users (id),
	CONSTRAINT fk_claim_eid FOREIGN KEY (EID) REFERENCES employer (EID),
);
