DROP TABLE IF EXISTS hours;
DROP TABLE IF EXISTS paycheck;
DROP TABLE IF EXISTS job;
DROP TABLE IF EXISTS claim;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS worker;
DROP TABLE IF EXISTS employer;
DROP TABLE IF EXISTS non_profit;


/* This is a very simple table for a mysql-php example */

CREATE TABLE Users (
  id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR (30) NOT NULL,
  phone VARCHAR (15) NOT NULL,
  hashedPass VARCHAR(255) NOT NULL,
  email VARCHAR(45) UNIQUE NOT NULL,
  PRIMARY KEY (ID)
);
CREATE TABLE worker (
	WID INT unsigned AUTO_INCREMENT,
	W_NAME VARCHAR (30) NOT NULL,
	PHONE_NUM VARCHAR (15)  NOT NULL,
	W_EMAIL VARCHAR (40) NOT NULL,
	PRIMARY KEY (WID)
);

CREATE TABLE employer (
	EID INT unsigned AUTO_INCREMENT,
	E_NAME VARCHAR (30) NOT NULL,
	ADDRESS VARCHAR (100) NOT NULL,
	E_EMAIL VARCHAR (40) NOT NULL,
	PRIMARY KEY (EID)
);

CREATE TABLE job (
	JID INT unsigned AUTO_INCREMENT,
	WID INT UNSIGNED NOT NULL,
	EID INT UNSIGNED NOT NULL,
	PRIMARY KEY (JID, WID, EID),
	CONSTRAINT fk_job_wid FOREIGN KEY (WID) REFERENCES worker (WID),
	CONSTRAINT fk_job_eid FOREIGN KEY (EID) REFERENCES employer (EID)
);

CREATE TABLE hours (
	JID INT UNSIGNED NOT NULL,
	DAILY_HOURS FLOAT NOT NULL,
	DAILY_HOURS_DATE DATE NOT NULL,
	PRIMARY KEY (JID),
	CONSTRAINT fk_hours_jid FOREIGN KEY (JID) REFERENCES job (JID)
);

CREATE TABLE paycheck (
	JID INT UNSIGNED NOT NULL,
	HOURLY_WAGE INT(4) NOT NULL,
	NET_PAY INT(4) NOT NULL,
	HOURS_PAID_FOR FLOAT NOT NULL,
	START_DATE DATE NOT NULL,
	END_DATE DATE NOT NULL,
	PRIMARY KEY (JID),
	CONSTRAINT fk_paycheck_jid FOREIGN KEY (JID) REFERENCES job (JID)
);
	
	
CREATE TABLE non_profit (
	NPID INT unsigned AUTO_INCREMENT,
	NP_NAME VARCHAR (30) NOT NULL,
	NP_PHONE  VARCHAR (15) NOT NULL,
	NP_EMAIL VARCHAR(40) NOT NULL,
	PRIMARY KEY (NPID)
);

CREATE TABLE claim (
	WID INT UNSIGNED NOT NULL,
	EID INT UNSIGNED NOT NULL,
	NPID INT UNSIGNED NOT NULL,
	PRIMARY KEY (WID, EID, NPID),
	CONSTRAINT fk_claim_wid FOREIGN KEY (WID) REFERENCES worker (WID),
	CONSTRAINT fk_claim_eid FOREIGN KEY (EID) REFERENCES employer (EID),
	CONSTRAINT fk_claim_npid FOREIGN KEY (NPID) REFERENCES non_profit (NPID)
);
